pipeline {
    agent any

    tools {
        maven 'Maven3'   // Make sure Maven is installed and configured in Jenkins
        jdk 'JDK11'      // Ensure JDK is configured in Jenkins global tools
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/yeshwanthsai42-a11y/inetbankingV1.git',
                    credentialsId: 'github-pat-2'   // Replace with your Jenkins credential ID
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }
    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml'
        }
    }
}
